# site settings
title: Tam Phan
subtitle: Senior iOS Developer for Hire, Freelancer
email: tam09t4@gmail.com
description: Senior iOS Developer for Hire, Freelancer<br /> and experience working with Objective-C, Swift.
baseurl: "" # the subpath of your site, e.g. /blog forty-jekyll-theme
url: https://tam09t4.github.io
author:
street_address: 41 Le Duan
city: Da Nang
state: Hai Chau
zip_code: 550000
country: Viet Nam
phone: (+84) 121-363-1188
skype: pmtamit
facebook: https://www.facebook.com/PhanMinhTam

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
